# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20d334de7ac801b15f9f49a4abe03e9f9c46787df22da86c0b003d00c6dad34e16e3176fd61c0b5ab3548c47348f10d27e8e5f02e10c472c9f00cca9a722749a

test:
  secret_key_base: 946c9a2a3df579cd03170def4d5c2b47eaba5769eedee666fb6032c2ef46acfee2c89c65ae5ed4f253aa79945e7fdbdd1c8dcfc374b1446129ac24c4a2a07b40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
