# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85fa6a43d1967d9f17f01f70d89bb9dba9af2bec91c1b1621a970515ff1cc04521d3475e9c99dfc9af1a18fa55529fae05633536a9caa0365a3b01a55de0d81d

test:
  secret_key_base: 6c1d08833666a8ca9636de9b16fa6b707e9d2e8a15fa06936eb4e39bb118f5bdea2494efe8c78aad546a2ea774edd725496def4ba621b225764f49b282dde282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
